import { recommendProject } from '@/lib/recommendation';
import { type ProjectInput } from '@/lib/domain';
import { ProjectBriefSchema, type PlanPhase, type PlanTool, type ProjectBrief, type ProjectPlan, type ProjectRisk } from './types';

const label=(value:string)=>value==='unknown'||value==='undecided'?'未確認':value;
function recommendationInput(brief:ProjectBrief):ProjectInput {
  // The legacy recommendation engine requires concrete values. Unknowns use broad,
  // non-restrictive review modes here and remain explicitly unresolved in the plan.
  return {gameType:brief.platform==='web'?'browser':brief.platform==='mobile'?'mobile':brief.dimension==='3d'?'3d':'2d',genre:['rpg','monster-collection','visual-novel','horror','action','puzzle'].includes(brief.genre)?brief.genre as ProjectInput['genre']:'other',platform:brief.platform==='unknown'?'multi-platform':brief.platform,engine:brief.engine==='unknown'?'undecided':brief.engine,budget:brief.budget==='unknown'?'flexible':brief.budget,experience:brief.experience==='unknown'?'intermediate':brief.experience,codingPreference:'assisted',assetRequirements:[...(brief.capabilities.includes('art-2d')?['2d-assets' as const]:[]),...(brief.capabilities.includes('assets-3d')||brief.dimension==='3d'?['3d-assets' as const]:[]),...(brief.capabilities.includes('animation')?['animation' as const]:[])],voiceRequirement:brief.capabilities.includes('voice')?'required':'none',musicRequirement:brief.capabilities.includes('music')?'required':'none',commercialIntent:brief.commercialIntent==='unknown'?'undecided':brief.commercialIntent,integrationImportance:brief.capabilities.includes('npc-dialogue')?'high':'low'};
}
const specificLoop=(brief:ProjectBrief)=>brief.genre==='monster-collection'?'探索 → 最初のモンスターとの遭遇 → 捕獲 → 編成':brief.genre==='visual-novel'?'開始 → 最初の選択肢 → 分岐結果 → セーブ／復帰':brief.genre==='horror'?'探索 → 脅威の予兆 → 回避 → 安全地点':brief.genre==='puzzle'?'ルール提示 → 代表問題 → 成否フィードバック':brief.genre==='rpg'?'探索 → 最初の戦闘 → 報酬 → セーブ':brief.genre==='action'?'移動 → 攻撃 → 被弾 → リトライ':'開始 → 主要操作 → 成否 → リトライ';
const engineRoot=(brief:ProjectBrief)=>brief.engine==='unity'?`Assets/\n  Scripts/\n  Data/\n  Scenes/\n  UI/\n  Audio/\nTests/`:brief.engine==='unreal'?`Content/\n  Blueprints/\n  Data/\n  Maps/\n  UI/\n  Audio/\nConfig/`:brief.engine==='godot'?`scenes/\nscripts/\nresources/\nassets/\n  ui/\n  audio/\ntests/`:`src/\n  core/\n  data/\n  ui/\nassets/\ntests/`;
const inputRefsFor=(stage:string,brief:ProjectBrief):string[]=>{
  const refs=[`公開先: ${label(brief.platform)}`,`エンジン: ${label(brief.engine)}`,`予算: ${label(brief.budget)}`,`利用目的: ${label(brief.commercialIntent)}`];
  if(stage==='voice')refs.push('必要工程: 音声');
  if(stage==='music-sfx')refs.push(`必要工程: ${brief.capabilities.includes('music')?'BGM':''}${brief.capabilities.includes('sfx')?'・効果音':''}`);
  if(stage==='visuals')refs.push('必要工程: 2Dアート');
  if(stage==='3d')refs.push(`表現: ${label(brief.dimension)}`,'必要工程: 3D素材');
  if(stage==='npc-dialogue')refs.push('必要工程: NPC・会話');
  if(stage==='code')refs.push(`制作経験: ${label(brief.experience)}`);
  return refs;
};
const planTool=(candidate:{service:import('@/lib/schema').Service;reason:string;evidence:string[];limitations:string[];unknowns:string[];manualChecks:string[]},role:PlanTool['role'],stage:string,brief:ProjectBrief):PlanTool=>({
  serviceSlug:candidate.service.slug,name:candidate.service.name,role,reason:candidate.reason,inputRefs:inputRefsFor(stage,brief),evidence:candidate.evidence,
  commercialUse:candidate.service.commercialUse,freePlan:candidate.service.freePlan,api:candidate.service.api,engineRelevance:candidate.service.engines,
  limitations:candidate.limitations,unknowns:candidate.unknowns,manualChecks:candidate.manualChecks,lastVerified:candidate.service.lastVerified,
  sources:candidate.service.sources.map(({label,url,type})=>({label,url,type})),
});

export function generateProjectPlan(raw:ProjectBrief):ProjectPlan {
  const brief=ProjectBriefSchema.parse(raw); const recommendations=recommendProject(recommendationInput(brief));
  const included=recommendations.stages.filter(stage=>stage.requirement!=='excluded');
  const phases:PlanPhase[]=included.map((stage,index)=>({id:stage.stage,title:stage.stage,objective:stage.deliverable,deliverables:[stage.deliverable],toolPath:stage.primary?[`${stage.primary.service.name}: ${stage.primary.reason}`]:[stage.manualFallback??'手動工程'],tools:[...(stage.primary?[planTool(stage.primary,'primary',stage.stage,brief)]:[]),...stage.alternatives.map(item=>planTool(item,'alternative',stage.stage,brief)),...stage.reviewCandidates.map(item=>planTool(item,'review',stage.stage,brief))],alternatives:stage.alternatives.map(item=>item.service.name),manualWork:stage.manualTasks,dependencies:index?[included[index-1].stage]:[],risks:[...stage.primary?.unknowns??[],...stage.primary?.manualChecks??[]],doneWhen:stage.acceptanceCriteria,handoff:stage.handoff}));
  const audio=phases.find(phase=>phase.id==='music-sfx');
  if(audio&&brief.capabilities.includes('music')&&brief.capabilities.includes('sfx')) { audio.objective='BGMと効果音を別々の成果物・検品基準で制作する'; audio.deliverables=['場面別BGM、ループ点、利用条件記録','操作・UI・環境別SFX、音量基準、利用条件記録']; audio.manualWork.push('BGMとSFXを別々に音量・ループ・場面適合で検品する'); }
  if(brief.capabilities.includes('localization')) { const integrationIndex=phases.findIndex(phase=>phase.id==='integration'); const preceding=integrationIndex>0?phases[integrationIndex-1].id:'code'; phases.splice(Math.max(0,integrationIndex),0,{id:'localization',title:'ローカライズ',objective:`${brief.locale==='ja-en'?'日本語・英語':'対象言語'}で同じゲーム状態を再現する`,deliverables:['文字列ID台帳','翻訳・レビュー済み文字列','言語切替ビルド'],toolPath:['翻訳支援の出力を文脈付きで人がレビューする'],tools:[],alternatives:['専門翻訳者へ依頼する'],manualWork:['UI収まり、固有名詞、文脈を実機確認する'],dependencies:[preceding],risks:['文脈欠落とUI崩れ'],doneWhen:['全文字列がID管理される','代表画面と言語切替を実機で通過する'],handoff:'レビュー記録付き文字列と検証ビルド'}); const integration=phases.find(phase=>phase.id==='integration'); if(integration)integration.dependencies=[...new Set([...integration.dependencies,'localization'])]; }
  const verticalSlice=[{id:'core-loop',title:specificLoop(brief),why:'最小の操作連鎖でゲームの成立性を検証できるため',outOfScope:['大量コンテンツ','最終演出','ストア公開作業'],doneWhen:['開始から結果まで中断せずプレイできる','観察した問題を記録できる']},{id:'save-build',title:'セーブ／復帰と最初の対象環境ビルド',why:'後戻りが大きいデータ保持と配布経路を早期に検証するため',outOfScope:['クラウドセーブ','全端末最適化'],doneWhen:['終了後も主要状態を復元できる','対象環境で起動できる']}];
  if(brief.genre==='monster-collection')verticalSlice.push({id:'first-set',title:'識別可能なモンスター3体と図鑑',why:'収集・識別・データIDの流れを小規模で検証するため',outOfScope:['大量の進化系','オンライン交換'],doneWhen:['3体を見分けて捕獲・編成できる','図鑑とセーブが同じ固定IDを使う']});
  if(brief.genre==='visual-novel')verticalSlice.push({id:'branch',title:'1つの選択肢と2つの短い分岐',why:'脚本、状態、表示、復帰の一連を検証するため',outOfScope:['全ルート','全音声収録'],doneWhen:['両分岐へ到達できる','分岐前セーブから復帰できる']});
  if(brief.genre==='rpg')verticalSlice.push({id:'quest-data',title:'1クエストの状態・報酬・セーブデータ',why:'進行不能につながる状態設計を先に検証するため',outOfScope:['長編シナリオ','大量の装備'],doneWhen:['受注から報酬まで固定IDで追跡できる','途中セーブから復帰できる']});
  if(brief.genre==='horror')verticalSlice.push({id:'horror-beat',title:'照明・環境音・脅威を含む1つの恐怖演出',why:'視認性と音響導線を小規模で検証するため',outOfScope:['複数チャプター','最終演出'],doneWhen:['複数の再生環境で予兆を認識できる','暗所でも操作と退路を判別できる']});
  if(brief.genre==='action')verticalSlice.push({id:'combat-frame',title:'1つの攻撃・被弾・リトライと入力受付表',why:'操作、判定、動きの同期を先に検証するため',outOfScope:['大量コンボ','オンライン対戦'],doneWhen:['攻撃判定と表示が同期する','入力遅延とフレーム時間を計測できる']});
  if(brief.genre==='puzzle')verticalSlice.push({id:'puzzle-rule',title:'代表3問と状態遷移・既知解',why:'解可能性と難易度曲線を小規模で検証するため',outOfScope:['大量の問題','デイリーチャレンジ'],doneWhen:['各問題に既知解がある','色や音だけに依存せず状態を判別できる']});
  if(brief.platform==='web')verticalSlice.push({id:'web-budget',title:'初回ロード・キーボード／タッチ入力のブラウザ検証',why:'配信容量と入力差を早期に検証するため',outOfScope:['全ブラウザ完全対応','オフライン対応'],doneWhen:['初回ロード量を記録する','キーボードとタッチで完走できる']});
  const assets=['UIワイヤーフレーム','アイコンと入力表示']; if(brief.capabilities.includes('art-2d'))assets.push('キャラクター／モンスター参照シート','背景またはタイル','2D VFX'); if(brief.capabilities.includes('assets-3d')||brief.dimension==='3d')assets.push('3Dモデル','テクスチャ／マテリアル','コリジョン'); if(brief.capabilities.includes('animation'))assets.push('アニメーションクリップと遷移表'); if(brief.capabilities.includes('voice'))assets.push('台詞ID・話者同意・音声ファイル'); if(brief.capabilities.includes('music'))assets.push('場面別BGMとループ記録'); if(brief.capabilities.includes('sfx'))assets.push('操作／UI／環境の効果音'); if(brief.capabilities.includes('localization'))assets.push('ローカライズ文字列台帳'); if(brief.capabilities.includes('trailer'))assets.push('ストア画像とトレーラー素材');
  const risks:ProjectRisk[]=[{id:'scope',title:'スコープ膨張',why:'生成素材を増やすほど統合と検品も増える',mitigation:'vertical slice外を明示し、代表素材だけを先に作る',verification:'各追加項目がsliceの完了条件に必要かレビューする'},{id:'rights',title:'生成物の権利・商用条件',why:brief.commercialIntent==='commercial'?'販売前に入力素材、生成時プラン、出力の条件確認が必要':'後から販売へ変えると条件が変わり得る',mitigation:'出典、生成日、契約プラン、同意を台帳化する',verification:'公開前に各公式規約と台帳を再照合する'}];
  if(brief.capabilities.some(x=>x==='art-2d'||x==='assets-3d'))risks.push({id:'consistency',title:'AI素材の一貫性',why:'反復生成で形状、色、比率が変わり得る',mitigation:'参照シートと許容差を固定する',verification:'代表素材を並べ、ゲーム画面内で検品する'});
  if(brief.platform==='mobile')risks.push({id:'mobile-performance',title:'モバイル性能',why:'生成アセットの容量と描画負荷が実機制約を超え得る',mitigation:'代表シーンに性能予算を置く',verification:'低めの対象実機でフレーム時間、メモリ、容量を測る'});
  if(brief.capabilities.includes('npc-dialogue'))risks.push({id:'runtime-ai',title:'実行時AIの費用・遅延・逸脱',why:'通信状態と利用量で体験と継続費が変動する',mitigation:'固定会話へのフォールバックと利用上限を設ける',verification:'10往復で遅延、失敗、逸脱、利用量を記録する'});
  const assumptions=['日程は入力されていないため納期を生成しません']; const materialFields=(['genre','dimension','platform','engine','budget','experience','team','commercialIntent',...(brief.capabilities.includes('localization')?['locale' as const]:[])] as const); const unresolved=materialFields.filter(field=>brief[field]==='unknown'||brief[field]==='undecided').map(field=>`${field} は未確認`);
  const summary=`${brief.idea}\nEngine: ${label(brief.engine)} / Platform: ${label(brief.platform)} / Dimension: ${label(brief.dimension)}\nScope: ${specificLoop(brief)} をvertical sliceとして完成させる。`;
  const master=`# 実装ブリーフ\n${summary}\n\n## 非目標\n- 大量コンテンツと最終演出は初期マイルストーンに含めない\n## 初期マイルストーン\n${verticalSlice.map(x=>`- ${x.title}: ${x.doneWhen.join(' / ')}`).join('\n')}\n## 制約\n- 生成コードをレビューし、依存ライセンスを記録する\n- 未入手アセットはプレースホルダー化する\n## テスト\n- コアループ、セーブ復帰、対象環境ビルドの再現手順を残す`;
  const engineUnknown=brief.engine==='unknown'||brief.engine==='undecided';
  const firstTask=engineUnknown ? `実装前にエンジン選定spikeを行ってください。${label(brief.platform)}向け候補を2つまで比較し、「${verticalSlice[0].title}」の主要操作、ビルド、アセット取込を最小検証してください。選定理由と未解決事項を記録し、大量実装はまだ行わないでください。` : `${label(brief.engine)}プロジェクトで「${verticalSlice[0].title}」の最小実装を作ってください。プレースホルダーを使い、${verticalSlice[0].doneWhen.join('、')}ことをテストしてください。大量コンテンツは追加しないでください。`;
  const genrePrompt=brief.genre==='horror'?'照明、無音、環境音、脅威の予兆を時系列で記述し、視認性と音量の検証点を列挙する。':brief.genre==='rpg'?'クエスト状態、固定ID、報酬、失敗条件、セーブ移行を表にし、進行不能テストを列挙する。':brief.genre==='action'?'入力受付、アニメーション、ヒットボックス、被弾、リトライをフレーム単位の受け入れ条件にする。':brief.genre==='puzzle'?'ルール、状態遷移、代表3問、既知解、詰み検出、色以外の状態表現を定義する。':brief.platform==='web'?'初回ロード容量、キーボードとタッチ入力、ブラウザ差を受け入れ条件にする。':`「${specificLoop(brief)}」の状態、入力、失敗時挙動、セーブ復帰を定義する。`;
  const today=engineUnknown?['候補を2つまでに絞り、比較する入力・ビルド・取込条件を固定する','各候補で同じ最小spikeを実行し、結果を比較表へ記録する','採用エンジン、選定理由、未解決事項をdecision recordへ残す']:['コアループと作らない機能を1ページに固定する',`「${verticalSlice[0].title}」のプレースホルダー版を作る`,'対象環境で起動し、問題を記録する'];
  return {version:1,brief,assumptions,unresolved,today,verticalSlice,phases,repositoryStructure:engineRoot(brief),masterBrief:{title:'Master implementation brief',content:master},firstTask:{title:'First task prompt',content:firstTask},agentsStarter:{title:'AGENTS.md starter',content:`# Project instructions\n- 最初の目標: ${verticalSlice[0].title}\n- 変更ごとにビルドとコアループを確認する\n- 生成コード、依存関係、素材ライセンスを人がレビューする\n- 未確認事項を事実として補完しない`},assetChecklist:[...new Set(assets)],prompts:[{id:'coding-first',taskId:'core-loop',title:`${brief.genre==='unknown'?'コアループ':brief.genre}制作レシピ`,content:genrePrompt}],risks,cost:{categories:['利用するAIサービスの契約・クレジット','人による制作・レビュー','対象端末・ストア公開','実行時API（使用する場合）'],note:'構造化された確定金額がないため合計は算出しません。無料枠、上限、商用条件、最新価格を各公式ページで確認してください。'}};
}
