import { cleanup,fireEvent,render,screen } from '@testing-library/react';
import { afterEach,describe,expect,it,vi } from 'vitest';
import { CompareClient } from '@/components/CompareClient';
import { getServices } from '@/lib/services';
const replace=vi.fn();afterEach(cleanup);
vi.mock('next/navigation',()=>({useSearchParams:()=>new URLSearchParams(),usePathname:()=>'/compare',useRouter:()=>({replace})}));
describe('compare',()=>{
  it('renders decision fields and selected tools',()=>{render(<CompareClient services={getServices()} initial={['github-copilot','cursor']}/>);expect(screen.getAllByText('GitHub Copilot').length).toBeGreaterThan(0);for(const label of ['料金','無料枠','商用利用','API','ゲームエンジン','プラットフォーム','主用途','長所','制約・弱点','最終確認日'])expect(screen.getAllByText(label).length).toBeGreaterThan(0)});
  it('enforces four selections and persistently explains the limit',()=>{render(<CompareClient services={getServices()} initial={getServices().slice(0,4).map(s=>s.slug)}/>);expect(screen.getAllByRole('status').some(node=>node.textContent?.includes('上限に達しました'))).toBe(true);const disabled=screen.getAllByRole('checkbox').filter(node=>(node as HTMLInputElement).disabled);expect(disabled.length).toBeGreaterThan(0);expect(disabled[0].closest('label')?.title).toBe('最大4件まで比較できます')});
  it('can remove and clear selections',()=>{render(<CompareClient services={getServices()} initial={['github-copilot','cursor']}/>);fireEvent.click(screen.getByRole('button',{name:'すべて解除'}));expect(screen.getByText('0 / 4')).toBeTruthy();expect(screen.getByText(/あと2件/)).toBeTruthy()});
  it('offers a differences-only mobile-friendly view',()=>{render(<CompareClient services={getServices()} initial={['github-copilot','cursor']}/>);expect(screen.getByText(/項目に差分/)).toBeTruthy();fireEvent.click(screen.getByLabelText('差分のみ表示'));expect(screen.queryAllByText('最終確認日')).toHaveLength(0);expect(screen.getAllByText('差分').length).toBeGreaterThan(0)});
  it('links unknown and conditional facts to direct official verification sources',()=>{render(<CompareClient services={getServices()} initial={['github-copilot']}/>);expect(screen.getAllByText('生成時プランの商用利用条件・権利範囲').length).toBeGreaterThan(0);expect(screen.getAllByText('API提供有無・対象プラン・利用上限').length).toBeGreaterThan(0);expect(screen.getAllByRole('link',{name:'公式料金 ↗'}).every(link=>(link as HTMLAnchorElement).href.startsWith('http'))).toBe(true);expect(screen.getAllByRole('link',{name:'公式規約 ↗'}).length).toBeGreaterThan(0)});
  it('exposes semantic desktop and paired mobile comparison structures',()=>{render(<CompareClient services={getServices()} initial={['github-copilot','cursor']}/>);expect(screen.getByRole('table',{name:/差分のある項目を先/})).toBeTruthy();expect(screen.getByRole('region',{name:'選択したツールの比較結果'})).toBeTruthy();expect(screen.getAllByRole('columnheader').length).toBe(3);expect(screen.getAllByRole('rowheader').length).toBeGreaterThan(0);expect(screen.getByText('GitHub Copilotの公式確認と次の行動')).toBeTruthy()});
});
