import type { Metadata } from 'next';
import Link from 'next/link';
import { ProjectIdeaForm } from '@/components/ProjectGeneratorClient';

export const metadata:Metadata={title:'作りたいゲームから制作ロードマップを作る',description:'ゲーム案を入力すると、今日やること、制作ロードマップ、使うAI、具体的なPrompt、完了条件を整理します。',alternates:{canonical:'/'},openGraph:{url:'/'}};
const examples=['Unityでモンスター収集RPG','Godotで2Dアクション','Steam向け3Dホラー','フルボイスのノベルゲーム','ブラウザ戦略ゲーム'];
export default function Home(){return <>
  <section className="studio-hero">
    <div className="hero-command"><p className="system-label">はじめてのAIゲーム制作ナビ</p><h1>ゲームを作ったことがなくても、<span>次の1作業から</span><span>完成へ進める。</span></h1><p className="lead">作りたいゲームを1文で書くと、<strong>使うAI、コピーする指示、実際の操作、できたと判断する条件</strong>を1ステップずつ返します。AIツールを探すだけの一覧ではありません。</p><ul className="hero-trust" aria-label="GameAI Hubで分かること"><li>今日やることは最大3つ</li><li>最初の目標は「ゲームが動く」</li><li>詰まった時の相談文も作成</li></ul><ProjectIdeaForm location="home"/></div>
    <aside className="deliverable-board" aria-label="入力後に得られる制作ナビの表示例"><header><div><span>入力後の表示例</span><strong>モンスター収集ゲーム</strong></div><small>最初の1作業</small></header><div className="board-now"><span>まず動かすもの</span><h2>1体対1体のバトル</h2><p>味方と敵を表示し、「たたかう」でHPが減り、勝敗とやり直しまで動かします。</p></div><dl className="board-gates"><div><dt>コピーするもの</dt><dd>1つのHTMLを作る、このゲーム専用のAI指示</dd></div><div><dt>できた条件</dt><dd>行動 → 勝敗 → やり直しを自分で操作できる</dd></div></dl><div className="board-evidence"><span>詰まったら</span><p><strong>いまの作業と成功条件</strong>を入れた相談文をコピーして、使用中のAIへそのまま渡せます。</p></div><ol className="board-route" aria-label="制作ナビの流れ"><li className="current"><b>01</b><span>動かす</span></li><li><b>02</b><span>確かめる</span></li><li><b>03</b><span>できた</span></li><li><b>04</b><span>次へ</span></li></ol></aside>
  </section>
  <section className="home-flow"><div className="section-head"><div><span className="system-label">HOW IT WORKS</span><h2>検索では終わらない、4つの判断。</h2></div><p>一般的なAI一覧は「候補」を返します。GameAI Hubは候補を制作工程へ接続します。</p></div><ol><li><b>01</b><h3>ゲームを説明</h3><p>決まっている条件だけを自由文で入力。</p></li><li><b>02</b><h3>成果物を決める</h3><p>いま作る1つと、明確な完了条件を表示。</p></li><li><b>03</b><h3>根拠を確かめる</h3><p>条件一致・制約・公式確認日を同じ場所で確認。</p></li><li><b>04</b><h3>次工程へ渡す</h3><p>Promptと成果物を次の制作作業へ接続。</p></li></ol></section>
  <section className="example-projects"><div><span className="system-label">プロジェクト例</span><h2>たとえば、こんな計画</h2></div><div className="example-list">{examples.map((item,index)=><Link key={item} href={`/project?idea=${encodeURIComponent(item)}`}><span>{String(index+1).padStart(2,'0')}</span><strong>{item}</strong><small>制作計画を作る →</small></Link>)}</div></section>
  <section className="roadmap-explainer"><div><span className="system-label">PRODUCTION HANDOFF</span><h2>AIではなく、成果物で工程をつなぐ。</h2><p>各工程のPromptを「作るもの」「完了条件」「次へ渡すもの」に接続。不要な音声や3D工程は計画へ加えません。</p></div><div className="blueprint-line"><span>企画<small>1ページ仕様</small></span><span>試作<small>操作build</small></span><span>素材<small>素材台帳</small></span><span>検証<small>QA記録</small></span><span>公開<small>候補build</small></span></div></section>
  <section className="home-resources"><article><span>AI DATABASE</span><h2>目的からAIを検証</h2><p>コード、声、3Dなど「作るもの」から候補と公式根拠を確認します。</p><Link href="/tools">目的から探す →</Link></article><article><span>GUIDES</span><h2>工程の判断を深掘り</h2><p>制作の進め方と、契約前に確認する条件を読み解きます。</p><Link href="/guides">ガイドを読む →</Link></article></section>
  <section className="final-project-cta"><span className="system-label">制作を始める</span><h2>まず、作りたいゲームを1文で。</h2><p>ツール選びの前に、最初のプレイ可能範囲と今日の作業を決めます。</p><Link className="button" href="/project">制作ロードマップを作る</Link></section>
  </>}
