import type { ReactNode } from 'react';
import Link from 'next/link';
import { ArticleProjectCta } from '@/components/ArticleProjectCta';
import { articleCategoryLabels, articlePath, type ArticleRecord } from '@/data/articles';
import { serializeJsonLd } from '@/lib/json-ld';
import { absoluteSiteUrl } from '@/lib/site';

export function ArticleFrame({article,children}:{article:ArticleRecord;children:ReactNode}){
 const path=articlePath(article);
 const articleJson={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt,author:{"@type":"Organization",name:article.author},publisher:{"@type":"Organization",name:'GameAI Hub',url:absoluteSiteUrl('/')},mainEntityOfPage:absoluteSiteUrl(path)};
 const breadcrumbs={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'ホーム',item:absoluteSiteUrl('/')},{"@type":"ListItem",position:2,name:'記事',item:absoluteSiteUrl('/articles/')},{"@type":"ListItem",position:3,name:article.title,item:absoluteSiteUrl(path)}]};
 return <article className="page-shell article-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd(articleJson)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd(breadcrumbs)}}/><nav className="breadcrumbs" aria-label="パンくず"><Link href="/">ホーム</Link><span>/</span><Link href="/articles">記事</Link><span>/</span><span>{article.title}</span></nav><header className="article-record"><span className="tag">{articleCategoryLabels[article.category]}</span><p>公開: <time dateTime={article.publishedAt}>{article.publishedAt}</time> ／ 更新: <time dateTime={article.updatedAt}>{article.updatedAt}</time></p><p>{article.editorialNote}</p></header>{children}<section className="article-related" aria-labelledby={`related-${article.slug}`}><p className="section-label">NEXT EVIDENCE</p><h2 id={`related-${article.slug}`}>次の判断に必要なページ</h2><ul>{article.related.map(link=><li key={link.href}><Link href={link.href}><span>{({article:'記事',guide:'ガイド',tool:'ツール',compare:'比較'} as const)[link.kind]}</span><strong>{link.label}</strong></Link></li>)}</ul></section><section className="sources"><p className="section-label">SOURCES & EDITORIAL</p><h2>情報源と更新方針</h2>{article.sources.length?<ul>{article.sources.map(source=><li key={source.url}><a href={source.url} rel="noopener" target="_blank">{source.label} ↗</a><span>{source.kind==='primary'?'一次資料':'実体験'}</span></li>)}</ul>:<p>この記事は運営者の実体験・意見を扱い、外部製品の仕様を根拠とする記事ではありません。</p>}<p>仕様・料金・規約を扱う場合は公開前と更新時に一次資料を確認し、確認できない情報は不明と記載します。更新基準は<Link href="/methodology">調査・評価方法</Link>をご覧ください。</p></section><ArticleProjectCta slug={article.slug} {...article.projectCta}/></article>
}
