export type EventName = 'tool_view'|'stack_view'|'stack_to_builder'|'compare_start'|'compare_view'|'outbound_click'|'affiliate_click'|'calculator_start'|'calculator_complete'|'diagnosis_start'|'diagnosis_complete'|'builder_start'|'builder_step'|'builder_complete';
type AnalyticsValue=string|string[]|number|boolean;
export type EventProperties=Partial<Record<'service'|'page'|'placement'|'services'|'stack'|'step'|'game_type'|'budget'|'sub_id'|'category'|'rule_version',AnalyticsValue>>;
type Gtag=(command:'event',eventName:string,params?:Record<string,unknown>)=>void;
const allowlist:Record<EventName,readonly (keyof EventProperties)[]>={tool_view:['service','page'],stack_view:['stack','page'],stack_to_builder:['stack','page'],compare_start:['services','page'],compare_view:['services','page'],outbound_click:['service','page','placement','sub_id'],affiliate_click:['service','page','placement','sub_id'],calculator_start:['category'],calculator_complete:['category'],diagnosis_start:['rule_version'],diagnosis_complete:['rule_version'],builder_start:['page'],builder_step:['step','page'],builder_complete:['page','game_type','budget']};
function safeValue(value:unknown):value is AnalyticsValue{return typeof value==='string'||typeof value==='number'||typeof value==='boolean'||(Array.isArray(value)&&value.every(item=>typeof item==='string'));}
export function sanitizeEventProperties(name:EventName,properties:EventProperties):Record<string,AnalyticsValue>{const clean:Record<string,AnalyticsValue>={};for(const key of allowlist[name]){const value=properties[key];if(safeValue(value))clean[key]=value;}return clean;}
export function track(name:EventName,properties:EventProperties={}){if(typeof window==='undefined')return;const safe=sanitizeEventProperties(name,properties);window.dispatchEvent(new CustomEvent('gameai:event',{detail:{name,properties:safe}}));if(process.env.NODE_ENV==='production'){const target=window as typeof window&{gtag?:Gtag;dataLayer?:unknown[]};if(target.gtag)target.gtag('event',name,safe);else{target.dataLayer=target.dataLayer||[];target.dataLayer.push(['event',name,safe]);}}else console.debug('[GameAI analytics]',name,safe);}
export function buildSubId(service:string,page:string,placement:string){return [service,page,placement].map(v=>v.replace(/[^a-z0-9_-]/gi,'-')).join('__').slice(0,100);}
